language: java

jdk:
  - oraclejdk8

script:
  - mvn clean -Dmaven.test.falure.ignore=true org.jacoco:jacoco-maven-plugin:report coveralls:report package
after_success:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN

notifications:
  slack: shanhonghao:pdqZbe3SSqGZahgfKsddxPE5
