language: java

jdk:
  - oraclejdk8

script:
  - mvn clean test jacoco:report
after_success:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN

notifications:
  slack: shanhonghao:pdqZbe3SSqGZahgfKsddxPE5